# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoisesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AZN', models.CharField(max_length=10)),
                ('USD', models.CharField(max_length=10)),
                ('EURO', models.CharField(max_length=10)),
                ('GBP', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USD', models.FloatField(max_length=255)),
                ('EURO', models.FloatField(max_length=255)),
                ('GBP', models.FloatField(max_length=255)),
                ('Date', models.CharField(default=datetime.datetime(2016, 12, 19, 14, 57, 53, 464228), max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Valyuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AZN', models.CharField(max_length=10)),
                ('USD', models.CharField(max_length=10)),
                ('EURO', models.CharField(max_length=10)),
                ('GBP', models.CharField(max_length=10)),
            ],
        ),
    ]
