# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 10:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20161219_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='Date',
            field=models.CharField(default=datetime.datetime(2016, 12, 19, 14, 58, 47, 704743), max_length=255),
        ),
    ]
