# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 11:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_auto_20161219_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='Date',
            field=models.CharField(default=datetime.datetime(2016, 12, 19, 15, 1, 48, 843890), max_length=255),
        ),
    ]
