# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_auto_20161219_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choise',
            old_name='AZN',
            new_name='cname',
        ),
        migrations.RemoveField(
            model_name='choise',
            name='EURO',
        ),
        migrations.RemoveField(
            model_name='choise',
            name='GBP',
        ),
        migrations.RemoveField(
            model_name='choise',
            name='USD',
        ),
        migrations.AlterField(
            model_name='currency',
            name='Date',
            field=models.CharField(default=datetime.datetime(2016, 12, 20, 16, 0, 24, 37481), max_length=255),
        ),
    ]
