# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 12:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0008_auto_20161220_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='Date',
            field=models.CharField(default=datetime.datetime(2016, 12, 20, 16, 1, 31, 801776), max_length=255),
        ),
    ]
