# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 09:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0009_auto_20161220_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choise',
        ),
        migrations.AlterField(
            model_name='currency',
            name='Date',
            field=models.CharField(default=datetime.datetime(2016, 12, 28, 13, 55, 45, 687997), max_length=255),
        ),
    ]
