# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0010_auto_20161228_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='Date',
            field=models.CharField(default=datetime.datetime(2016, 12, 28, 14, 35, 8, 923754), max_length=255),
        ),
    ]
