# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 07:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0012_auto_20161228_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='Date',
            field=models.CharField(default=datetime.datetime(2017, 1, 6, 11, 28, 5, 274433), max_length=255),
        ),
    ]
